version: "3"
services:
  nest-app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map the container port to the host port
    command: ["./wait-for-it.sh", "mysql-db:3306", "--", "npm", "run", "start:dev"]
    networks:
      - app-network
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysql-db

  mysql-db:
    container_name: db-app
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    ports:
      - "3306:3306"  # Map the container port to the host port
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  app-network:
    driver: bridge
volumes:
  mysql_data: